name: nike_authentic
services:
  web:
    image: nike_authentic:latest
    build:
      context: ./nike-web
    environment:
      - NODE_ENV=development
    ports:
      - "4200:4200"  
    volumes:
      - ./nike-web:/app 
      - /app/node_modules 
    stdin_open: true
    tty: true