spring:
  config:
    import: "optional:file:.env"
  cloudinary:
    cloud_name: ${CLOUD_NAME}
    api_key: ${API_KEY}
    api_secret: ${API_SECRET}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: duylee233
    url: jdbc:mysql://localhost:3306/product

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
